<?php
use yii\helpers\Html;
//use yii\bootstrap\Nav;
//use yii\bootstrap\NavBar;
//use yii\widgets\Breadcrumbs;
use yii\widgets\Menu;
use app\assets\AppAsset;


/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);

$this->registerJsFile('//repo.wsu.edu/spine/develop/spine.min.js', ['depends' => [yii\web\JqueryAsset::className()]]);

$this->registerJs('
$( document ).ready(function() {
    console.log( "ready!" );
	$("#logout a").click(function(event){
	
	  event.preventDefault();
	  $.ajax({
		url: "/portal/user/logout",
		type: "POST",
		success: function() {
			
			console.log( "ready!" );
		}
	    
	  });
	});
});				  

');

?>
<?php $this->beginPage() ?>

<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-svg lt-ie9 lt-ie8 lt-ie7" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 7]><html class="no-svg lt-ie9 lt-ie8" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if IE 8]><html class="no-svg lt-ie9" lang="<?= Yii::$app->language ?>"> <![endif]-->
<!--[if gt IE 8]><!--><html lang="<?= Yii::$app->language ?>"><!--<![endif]-->

<head>

    <meta charset="<?= Yii::$app->charset ?>"/>

    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://repo.wsu.edu/spine/develop/spine.min.css" rel="stylesheet" type="text/css" />
    <?php $this->head() ?>

	<!-- FAVICON -->
	<link rel="shortcut icon" href="https://repo.wsu.edu/spine/1/favicon.ico" />

	<!-- STYLESHEETS -->
	
	<!-- Your custom stylesheets here -->
    <link href="/portal/css/bootstrap-theme.css" rel="stylesheet" type="text/css" />
    <link href="/portal/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="/portal/css/style.css" rel="stylesheet" type="text/css" />

	<!-- RESPOND -->
	<meta name="viewport" content="width=device-width, user-scalable=yes">

	<!-- COMPATIBILITY -->
	<!--[if lt IE 9]><script src="https://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<noscript><style>#spine .spine-sitenav ul ul li { display: block !important; }</style></noscript>

	<!-- DOCS -->
	<link type="text/plain" rel="author" href="https://repo.wsu.edu/spine/1/authors.txt">
	<link type="text/html" rel="help" href="https://brand.wsu.edu">
   
	<!-- BASE URL -->
	<base href="/" />

</head>

<body class="">
<?php $this->beginBody() ?>

<!-- WRAPPING -->
<div id="jacket" class="colors-orange">
<div id="binder" class=" hybrid">
<!-- CONTENT -->
<main>

	<!-- Responsive Sections -->
	<section class="layout marginalize">
		<!--
		LAYOUTS: Place your preferred layout and content here.
		Layouts available are single (1 column), halves (2), thirds
		(3), quarters (4), side-left (2), side-right (2), margin-left (2),
		margin-right (2), and triptych (3). -->
		<div class="column one">
	        <header class="main-header">
                <div class="header-group hgroup guttered padded-bottom short">

                    <sup class="sup-header" data-section="News" data-pagetitle="Better Plantlets for Better Plants" data-posttitle="Better Plantlets for Better Plants" data-default="CAHNRS Department of Horticulture" data-alternate="<a href=&quot;http://genomics.wsu.edu/&quot; rel=&quot;home&quot;>Genomics Lab</a>"><span class="sup-header-default">CAHNRS Department of Horticulture</span></sup>
                    <sub class="sub-header" data-sitename="Genomics Lab" data-pagetitle="Better Plantlets for Better Plants" data-posttitle="Better Plantlets for Better Plants" data-default="Genomics Lab" data-alternate="News"><span class="sub-header-default">Genomics Lab</span></sub>

                </div>
        	</header>
            <section class="content">
                <?= $content ?>
            </section>
            
        </div>
		<!--<div class="column two"></div>
		<div class="column three"></div>
		<div class="column four"></div>-->
	</section>
</main>
<!-- /CONTENT -->

<!-- SPINE -->
<div id="spine" class="spine-column white" ">
<div id="glue" class="spine-glue" style="min-height: 960px;">

<header class="spine-header">
	<a href="https://wsu.edu/" id="wsu-signature" class="spine-signature">Washington State University</a>
</header>

<!-- ACTIONS -->
<section id="wsu-actions" class="spine-actions">



	<!-- Actions generated by spine.js end up here -->
</section><!--/#wsu-actions-->

<section id="spine-navigation" class="spine-navigation">

	<nav class="spine-sitenav">

	<?php
echo Menu::widget([
    'activeCssClass'=>'current active dogeared',
    'items' => [
        // Important: you need to specify url as 'controller/action',
        // not just as 'controller' even if default action is used.
        ['label' => 'Site Home', 'url' => ['/site/index']],
        ['label' => 'Download Files', 'url' => ['/download/index'], 'visible' => !Yii::$app->user->isGuest],
        ['label' => 'Request Access', 'url' => ['/request/index'], 'visible' => !Yii::$app->user->isGuest],
        ['label' => 'Manage Access Requests', 'url' => ['/request-manager/index'], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->can("admin")],
        ['label' => 'Manage Users', 'url' => ['/user/admin'], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->can("admin")],
        ['label' => 'Manage Groups', 'url' => ['/filegroup/index'], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->can("admin")],
		['label' => 'Manage Logs', 'url' => ['/log/index'], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->can("admin")],
        ['label' => 'Manage Files', 'url' => ['/file/index'], 'visible' => !Yii::$app->user->isGuest && Yii::$app->user->can("admin")],
		['label' => 'Manage Profile', 'url' => ['/user/account'], 'visible' => !Yii::$app->user->isGuest],
		['label' => 'Login', 'url' => ['/user/login'], 'visible' => Yii::$app->user->isGuest],
		['label' => 'Create Account', 'url' => ['/user/register'], 'visible' => Yii::$app->user->isGuest],
		['label' => 'Logout (' . Yii::$app->user->displayName . ')', 'options'=>['id'=>'logout'],'url' => ['/portal/user/logout'], 'visible' => !Yii::$app->user->isGuest],
		['label' => 'Contact Us', 'url' => ['/site/contact'], 'visible' => !Yii::$app->user->isGuest],
    ],
]);	

	?>

	</nav>

<nav id="spine-offsitenav" class="spine-offsitenav">
	<ul><li id="menu-item-1579"><a href="https://www.applyweb.com/public/inquiry?wsuuinq" class="external">Request Info</a></li>
<li id="menu-item-1580"><a href="http://admission.wsu.edu/visits/index.html" class="external">Visit</a></li>
<li id="menu-item-1581"><a href="http://admission.wsu.edu/applications/index.html" class="external">Apply</a></li>
<li id="menu-item-1582"><a href="http://cahnrs.wsu.edu/alumni/give/" class="external">I want to GIVE</a></li>
</ul></nav>
</nav>

</section><!-- #navigation -->

<!-- Social and Global Links -->
<footer class="spine-footer">
	<nav id="wsu-social-channels" class="spine-social-channels">
		<ul>
			<li class="facebook-channel"><a href="https://facebook.com/wsupullman">Facebook</a></li>
			<li class="twitter-channel"><a href="https://twitter.com/wsupullman">Twitter</a></li>
			<li class="youtube-channel"><a href="https://www.youtube.com/washingtonstateuniv">YouTube</a></li>
			<li class="directory-channel"><a href="http://social.wsu.edu">Directory</a></li>
		</ul>
	</nav>
	<nav id="wsu-global-links" class="spine-global-links">
		<ul>
			<li class="mywsu-link"><a href="https://my.wsu.edu/">myWSU</a></li>
			<li class="access-link"><a href="http://access.wsu.edu/">Access</a></li>
			<li class="policies-link"><a href="http://policies.wsu.edu/">Policies</a></li>
			<li class="copyright-link"><a href="http://copyright.wsu.edu">&copy;</a></li>
		</ul>
	</nav>
</footer>

</div><!--/glue-->
</div><!--/spine-->
<!-- /SPINE -->

</div><!--/cover-->
</div><!--/jacket-->
<!-- /WRAPPING -->

<!-- CONTACT INFO: Adjust the sample contact info below to reflect appropriate contact information. -->
<div id="contact-details" itemscope itemtype="http://schema.org/Organization"> 
	<span itemprop="department"  content="University Unit"></span> 
	<span itemprop="name" content="Washington State University"></span> 
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
		<span itemprop="location" content="Your location"></span>
		<span itemprop="streetAddress" content="Your PO Box"></span>
		<span itemprop="addressLocality" content="Pullman"></span>
		<span itemprop="addressRegion" content="WA"></span>
		<span itemprop="postalCode" content="99164"></span>
	</div>
	<span itemprop="telephone" content="(509) 335-3564"></span>
	<span itemprop="email" content="your-contact-email@wsu.edu"></span>
	<span itemprop="contactPoint" content="http://contactpage.wsu.edu"></span>
	<span itemprop="url" content="http://your-unit.wsu.edu"></span>
</div>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

